# Generated by Django 5.2.5 on 2025-09-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary_Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_field0', models.CharField(max_length=2500)),
                ('published_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
