# Generated by Django 5.2.5 on 2025-09-27 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary_entries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary_entry',
            old_name='entry_field0',
            new_name='entry_field',
        ),
    ]
