# Generated by Django 5.2.5 on 2025-10-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_entries', '0002_rename_entry_field0_diary_entry_entry_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotions_custom_code', models.CharField(choices=[('HP', 'happines'), ('SN', 'sadness'), ('AG', 'anger'), ('FR', 'fear'), ('SP', 'surprise'), ('DG', 'disgust')], max_length=2)),
                ('emotion_name', models.CharField(max_length=25)),
                ('emotion_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='diary_entry',
            name='emotion_descriptors',
            field=models.ManyToManyField(db_table='diary_entry_emotions', to='diary_entries.emotions'),
        ),
    ]
